name: "gradle-setup"

inputs: {}

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3