name: Pre Merge Checks

on:
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    permissions:
      security-events: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Gradle
        uses: ./.github/action/gradle-setup

      - name: gradlew permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload Debug .apk
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  detekt:
    permissions:
      security-events: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Gradle
        uses: ./.github/action/gradle-setup

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Upload Detekt Report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          category: detekt
