name: Pre Merge Checks

on:
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  pull request checks:

    permissions:
      security-events: write
      actions: read
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: gradlew permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug

      - name: Run Detekt
        run: ./gradlew detekt

      - uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: app/build/reports/detekt/detekt.sarif
          category: detekt
