name: Pull Request CI

on:
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  setup_gradle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: gradlew permission
        run: chmod +x gradlew

  build:
    needs: setup_gradle

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build --configuration-cache --debug


  detekt:
    needs: setup_gradle

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Detekt
        run: ./gradlew detekt

      - name: ls
        run: cd app/build/reports/detekt

      - name: Upload Detekt Reports
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: app/build/reports/detekt/detekt.sarif
